/*
    Renzo Macchi
    Santiago Claveré
*/
package Interfaz;

import Dominio.Sistema;

public class vGestionLibrerias extends javax.swing.JFrame {
    private Sistema modelo;
    
    public vGestionLibrerias() {
        initComponents();
    }
    
    public vGestionLibrerias(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        btnRegistrarEditorial = new javax.swing.JMenuItem();
        btnRegistrarGenero = new javax.swing.JMenuItem();
        btnRegistrarAutor = new javax.swing.JMenuItem();
        btnRegistrarLibro = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        btnRegistrarVenta = new javax.swing.JMenuItem();
        btnAnularVenta = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        btnConsultaLibros = new javax.swing.JMenuItem();
        btnConsultaVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de librerias - Realizado por Santiago Clavere y Renzo Macchi");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Registros");

        btnRegistrarEditorial.setMnemonic('o');
        btnRegistrarEditorial.setText("Registrar editorial");
        btnRegistrarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEditorialActionPerformed(evt);
            }
        });
        fileMenu.add(btnRegistrarEditorial);

        btnRegistrarGenero.setMnemonic('s');
        btnRegistrarGenero.setText("Registrar genero");
        btnRegistrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGeneroActionPerformed(evt);
            }
        });
        fileMenu.add(btnRegistrarGenero);

        btnRegistrarAutor.setMnemonic('a');
        btnRegistrarAutor.setText("Registrar autor");
        btnRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAutorActionPerformed(evt);
            }
        });
        fileMenu.add(btnRegistrarAutor);

        btnRegistrarLibro.setMnemonic('x');
        btnRegistrarLibro.setText("Registrar libro");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });
        fileMenu.add(btnRegistrarLibro);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Ventas");

        btnRegistrarVenta.setMnemonic('t');
        btnRegistrarVenta.setText("Registro de venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });
        editMenu.add(btnRegistrarVenta);

        btnAnularVenta.setMnemonic('y');
        btnAnularVenta.setText("Anular venta");
        btnAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularVentaActionPerformed(evt);
            }
        });
        editMenu.add(btnAnularVenta);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Consultas");

        btnConsultaLibros.setMnemonic('c');
        btnConsultaLibros.setText("Consulta de libros");
        btnConsultaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaLibrosActionPerformed(evt);
            }
        });
        helpMenu.add(btnConsultaLibros);

        btnConsultaVentas.setMnemonic('a');
        btnConsultaVentas.setText("Consulta de ventas");
        btnConsultaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaVentasActionPerformed(evt);
            }
        });
        helpMenu.add(btnConsultaVentas);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed
        //Abrir Ventana para Registrar un Libro
        vRegistroLibro rl = new vRegistroLibro(this.modelo);
        rl.setVisible(true);
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    private void btnRegistrarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEditorialActionPerformed
        //Abrir Ventana para Registrar una Editorial
        vRegistroEditorial re = new vRegistroEditorial(this.modelo);
        re.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarEditorialActionPerformed

    private void btnRegistrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGeneroActionPerformed
        //Abrir Ventana para Registrar un Genero
        vRegistroGenero rg = new vRegistroGenero(this.modelo);
        rg.setVisible(true);
    }//GEN-LAST:event_btnRegistrarGeneroActionPerformed

    private void btnConsultaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaVentasActionPerformed
        //Abrir Ventana para Consultar una Venta
        vConsultaVentas cv = new vConsultaVentas(this.modelo);
        cv.setVisible(true);
    }//GEN-LAST:event_btnConsultaVentasActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        //Abrir Ventana para Registrar una Venta
        vVentaLibros vl = new vVentaLibros(this.modelo);
        vl.setVisible(true);
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularVentaActionPerformed
        // TODO add your handling code here:
        vAnularVenta av = new vAnularVenta(this.modelo);
        av.setVisible(true);
        
    }//GEN-LAST:event_btnAnularVentaActionPerformed

    private void btnConsultaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaLibrosActionPerformed
        vConsultaLibros cl = new vConsultaLibros(this.modelo);
        cl.setVisible(true);
    }//GEN-LAST:event_btnConsultaLibrosActionPerformed

    private void btnRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAutorActionPerformed
        vRegistroAutor ra1 = new vRegistroAutor(modelo);
        ra1.setVisible(true);
    }//GEN-LAST:event_btnRegistrarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vGestionLibrerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vGestionLibrerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vGestionLibrerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vGestionLibrerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vGestionLibrerias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAnularVenta;
    private javax.swing.JMenuItem btnConsultaLibros;
    private javax.swing.JMenuItem btnConsultaVentas;
    private javax.swing.JMenuItem btnRegistrarAutor;
    private javax.swing.JMenuItem btnRegistrarEditorial;
    private javax.swing.JMenuItem btnRegistrarGenero;
    private javax.swing.JMenuItem btnRegistrarLibro;
    private javax.swing.JMenuItem btnRegistrarVenta;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
